apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: vcmts-profile0
spec:
  cpu:
    isolated: '2-31,34-63,66-95,98-127'
    reserved: '0-1,32-33,64-65,96-97'
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 102
      node: 0
      size: 1G
    - count: 102
      node: 1
      size: 1G
  nodeSelector:
    node-role.kubernetes.io/vcmts: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
