{
 "title": "Downstream Processing (Per SG)",
 "tags": [ "vCMTS" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Scenario_One",
    "query": "SHOW TAG Values with key =\"host\""
   },
   {
    "name": "Scenario_Two",
    "query": "SHOW TAG Values with key =\"host\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 align = \"center\">$Scenario_One</h1>"
   },
   "content": "<h1 align = \"center\">$Scenario_One</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<h1 align = \"center\">$Scenario_Two</h1>"
   },
   "content": "<h1 align = \"center\">$Scenario_Two</h1>"
  },
  {
   "title": "RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_downstream_bits_per_second_rx_total{exported_instance=\"$Scenario_One\"})/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_average_frame_size_per_second_rx{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "average_frame_size_per_second" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Frame TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_downstream_bits_per_second_tx_total{exported_instance=\"$Scenario_One\"})/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_average_frame_size_per_second_tx{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_downstream_bits_per_second_rx_total{exported_instance=\"$Scenario_Two\"})/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT distinct(\"value\") /1000000000 FROM \"downstream_rx\" WHERE (\"type\" = 'bits_per_second' AND \"type_instance\" = 'rx') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_average_frame_size_per_second_rx{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "average_frame_size_per_second" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Frame TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_downstream_bits_per_second_tx_total{exported_instance=\"$Scenario_Two\"})/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_average_frame_size_per_second_tx{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_second_rx_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_second_rx_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_second_tx_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_second_tx_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_dropped_per_second_rx_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_dropped_per_second_rx_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_sched_dropped_per_second_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sched_dropped_per_second" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_dropped_per_second_tx_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_sched_dropped_per_second_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sched_dropped_per_second" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_dropped_per_second_tx_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "# Cycles" }
   ],
   "targets": [
    {
     "alias": "TX",
     "expr": "collectd_downstream_downstream_cycles_rx{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "RX",
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "downstream_cycles" }
     ]
    },
    {
     "expr": "collectd_downstream_downstream_cycles_cm_lookup{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "CM Lookup"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_sub_mgmt{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Sub_Mgt"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_filtering{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Filtering"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_classification{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Classification"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_qos{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "QOS"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_upper_lower_mac_xfer{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Lower Mac Transfer"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_crc_encryption{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "CRC & Encryption"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_docsis_framing{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "DOCSIS Framing"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_depi_encap{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Depi Encapsulation"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_tx{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Latency",
     "expr": "collectd_downstream_packet_latency_jitter{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Jitter",
     "measurement": "downstream_average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packet_latency" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_downstream_packet_latency_average{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "# Cycles" }
   ],
   "targets": [
    {
     "alias": "TX",
     "expr": "collectd_downstream_downstream_cycles_rx{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "RX",
     "measurement": "downstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "downstream_cycles" }
     ]
    },
    {
     "expr": "collectd_downstream_downstream_cycles_cm_lookup{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "CM Lookup"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_sub_mgmt{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Sub_Mgt"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_filtering{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Filtering"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_classification{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Classification"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_qos{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "QOS"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_upper_lower_mac_xfer{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Lower Mac Transfer"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_crc_encryption{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "CRC & Encryption"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_docsis_framing{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "DOCSIS Framing"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_depi_encap{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Depi Encapsulation"
    },
    {
     "expr": "collectd_downstream_downstream_cycles_tx{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Latency",
     "expr": "collectd_downstream_packet_latency_jitter{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Jitter",
     "measurement": "downstream_average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packet_latency" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_downstream_packet_latency_average{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Empty",
     "expr": "collectd_downstream_rx_dequeue_per_second_pkts_present_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Non Empty",
     "measurement": "downstream_pkts_not_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "expr": "collectd_downstream_rx_dequeue_per_second_pkts_not_present_total{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Empty"
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Empty",
     "expr": "collectd_downstream_rx_dequeue_per_second_pkts_present_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Non Empty",
     "measurement": "downstream_pkts_not_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "expr": "collectd_downstream_rx_dequeue_per_second_pkts_not_present_total{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Empty"
    }
   ]
  },
  {
   "title": "Cable Modem Lookups",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "expr": "collectd_downstream_cm_lookup_unmatched{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Unmatched",
     "measurement": "downstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "expr": "collectd_downstream_cm_lookup_matched{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Matched"
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_cm_lookup{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "Cable Modem Lookups",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "expr": "collectd_downstream_cm_lookup_unmatched{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Unmatched",
     "measurement": "downstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "expr": "collectd_downstream_cm_lookup_matched{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Matched"
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_packets_per_cm_lookup{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_active_cms_per_second_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_active_cms_per_second_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_ip_addr_per_cm{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_ip_addr_per_cm{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Filtering",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched Permitted",
     "expr": "collectd_downstream_filter_matched_deny{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Match Denied",
     "measurement": "downstream_matched_permit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "filter" }
     ]
    },
    {
     "expr": "collectd_downstream_filter_unmatched{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Unmatched"
    },
    {
     "expr": "collectd_downstream_filter_matched_permit{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Matched Permitted"
    }
   ]
  },
  {
   "title": "Aggregate Classification",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Unmatched",
     "expr": "collectd_ds_per_cm_classifier_matched_ipv4{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Matched",
     "measurement": "downstream_unmatched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "classifier" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_classifier_unmatched{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Unmatched"
    }
   ]
  },
  {
   "title": "Matches per Classifier Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPV4",
     "expr": "collectd_ds_per_cm_classifier_matched_icmp{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ICMP",
     "measurement": "ds_per_cm_matched_ipv4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "classifier" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "0" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_classifier_matched_llc{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "LLC"
    },
    {
     "expr": "collectd_ds_per_cm_classifier_matched_ipv4{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "IPV4"
    }
   ]
  },
  {
   "title": "Aggregate Filtering",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched Permitted",
     "expr": "collectd_downstream_filter_matched_deny{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Match Denied",
     "measurement": "downstream_matched_permit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "filter" }
     ]
    },
    {
     "expr": "collectd_downstream_filter_unmatched{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Unmatched"
    },
    {
     "expr": "collectd_downstream_filter_matched_permit{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Matched Permitted"
    }
   ]
  },
  {
   "title": "Aggregate Classification",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Unmatched",
     "expr": "collectd_ds_per_cm_classifier_matched_ipv4{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Matched",
     "measurement": "downstream_unmatched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "classifier" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_classifier_unmatched{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Unmatched"
    }
   ]
  },
  {
   "title": "Matches per Classifier Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPV4",
     "expr": "collectd_ds_per_cm_classifier_matched_icmp{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ICMP",
     "measurement": "ds_per_cm_matched_ipv4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "classifier" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "0" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_classifier_matched_llc{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "LLC"
    },
    {
     "expr": "collectd_ds_per_cm_classifier_matched_ipv4{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "IPV4"
    }
   ]
  },
  {
   "title": "Bitrate per SF Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (bps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_bits_per_second" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "Frame Rate per SF Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Frame Rate (kpps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "ds_per_cm_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "ds_per_cm_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "ds_per_cm_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "ds_per_cm_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "ds_per_cm_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate per SF Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (bps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_bits_per_second" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_bits_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "Frame Rate per SF Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Frame Rate (kpps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "ds_per_cm_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "ds_per_cm_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "ds_per_cm_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "ds_per_cm_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_ds_per_cm_sf_queue_packets_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "ds_per_cm_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "sf_queue_packets_per_second" }
     ]
    }
   ]
  },
  {
   "title": "# Times SF Queue Selected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "# Times Selected" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sf_queue_selects_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "# Times SF Queue Selected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "# Times Selected" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_5_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_cm_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "sf_queue_selects_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_4_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_3_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_2_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_1_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_cm_sf_queue_selects_per_second_0_total{ds_per_cm=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "Bitrate per Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (bps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate per Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (bps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_ds_per_channel_channel_bits_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "ds_per_channel_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "channel_bits_per_second" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Rate per Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Rate (FPS)" }
   ],
   "targets": [
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "0"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "5"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"10\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "10"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"14\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "14"
    }
   ]
  },
  {
   "title": "Frame Rate per Channel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Rate (FPS)" }
   ],
   "targets": [
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "0"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "5"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"10\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "10"
    },
    {
     "expr": "collectd_ds_per_channel_channel_packets_per_second_total{ds_per_channel=\"14\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "14"
    }
   ]
  },
  {
   "title": "# Times Channels Selected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "# Times Selected" }
   ],
   "targets": [
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "0"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "5"
    }
   ]
  },
  {
   "title": "# Times Channels Selected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "# Times Selected" }
   ],
   "targets": [
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"0\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "0"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"1\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "1"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"2\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "2"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"3\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "3"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"4\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "4"
    },
    {
     "expr": "collectd_ds_per_channel_channel_selects_per_second_total{ds_per_channel=\"5\",exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "5"
    }
   ]
  },
  {
   "title": "Packet CRC Re-Generation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Generated",
     "expr": "collectd_downstream_crc_generated{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Generated",
     "measurement": "downstream_generated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Not Generated",
     "expr": "collectd_downstream_crc_not_generated{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Not Generated",
     "measurement": "downstream_not_generated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Encryption",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Aes",
     "expr": "collectd_downstream_crypto_algo_none{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "downstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Des",
     "expr": "collectd_downstream_crypto_algo_des{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "DES",
     "measurement": "downstream_des",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "None",
     "expr": "collectd_downstream_crypto_algo_aes{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AES",
     "measurement": "downstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "expr": "collectd_downstream_crypto_accel_qat{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "QAT",
     "measurement": "downstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "crypto_accel" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "QAT",
     "expr": "collectd_downstream_crypto_accel_aesni{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AESNI",
     "measurement": "downstream_qat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "crypto_accel" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet CRC Re-Generation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Generated",
     "expr": "collectd_downstream_crc_generated{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Generated",
     "measurement": "downstream_generated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Not Generated",
     "expr": "collectd_downstream_crc_not_generated{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Not Generated",
     "measurement": "downstream_not_generated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Encryption",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Aes",
     "expr": "collectd_downstream_crypto_algo_none{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "downstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Des",
     "expr": "collectd_downstream_crypto_algo_des{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "DES",
     "measurement": "downstream_des",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "None",
     "expr": "collectd_downstream_crypto_algo_aes{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AES",
     "measurement": "downstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 80 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "expr": "collectd_downstream_crypto_accel_qat{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "QAT",
     "measurement": "downstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "crypto_accel" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "QAT",
     "expr": "collectd_downstream_crypto_accel_aesni{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AESNI",
     "measurement": "downstream_qat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "crypto_accel" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frame Encoding",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 87 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frame Encoding",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 87 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "PSP Segments per DEPI Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "% DEPI Frames" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_7{exported_instance=\"$Scenario_One\"}\t\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "7",
     "measurement": "downstream_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_6{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "6",
     "measurement": "downstream_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_5{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "downstream_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_4{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "downstream_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_3{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "downstream_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_2{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "downstream_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "6",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_1{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "downstream_6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "7",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_0{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "downstream_7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    }
   ]
  },
  {
   "title": "#DOCSIS Frames per DEPI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 90 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_depi" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "PSP Segments per DEPI Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "% DEPI Frames" }
   ],
   "targets": [
    {
     "alias": "0",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_7{exported_instance=\"$Scenario_Two\"}\t\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "7",
     "measurement": "downstream_0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "1",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_6{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "6",
     "measurement": "downstream_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "2",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_5{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "5",
     "measurement": "downstream_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "3",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_4{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "4",
     "measurement": "downstream_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "4",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_3{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "3",
     "measurement": "downstream_4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "5",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_2{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "2",
     "measurement": "downstream_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "6",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_1{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1",
     "measurement": "downstream_6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    },
    {
     "alias": "7",
     "expr": "collectd_downstream_times_n_psp_seg_per_depi_0{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "0",
     "measurement": "downstream_7",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "times_n_psp_seg_per_depi" }
     ]
    }
   ]
  },
  {
   "title": "#DOCSIS Frames per DEPI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 90 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_downstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_depi" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DEPI Frame Encoding",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 93 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Partial",
     "expr": "collectd_downstream_depi_frames_full{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Full",
     "measurement": "downstream_partial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "depi_frames" }
     ]
    },
    {
     "alias": "Full",
     "expr": "collectd_downstream_depi_frames_partial{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Partial",
     "measurement": "downstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "depi_frames" }
     ]
    }
   ]
  },
  {
   "title": "DEPI Frame Encoding",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 93 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Partial",
     "expr": "collectd_downstream_depi_frames_full{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Full",
     "measurement": "downstream_partial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "depi_frames" }
     ]
    },
    {
     "alias": "Full",
     "expr": "collectd_downstream_depi_frames_partial{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Partial",
     "measurement": "downstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "depi_frames" }
     ]
    }
   ]
  }
 ]
}