{
 "title": "SystemSummary",
 "tags": [ "vCMTS" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 } },
  { "type": "pierosavi-imageit-panel", "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 3 },
   "options": {
    "content": "<p style=\"text-align: center;font-size:30px;\">\r\nUpstream\r\n</p>\r\n"
   },
   "content": "<h1 align = \"center\">Upstream</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 3 },
   "options": {
    "content": "<p style=\"text-align: center;font-size:30px;\">\r\nDownstream\r\n</p>\r\n"
   },
   "content": "<h1 align = \"center\">Downstream</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": {
    "content": "<p style=\"text-align: center;font-size:30px;\">\r\nConfiguration\r\n</p>"
   },
   "content": "<h1 align = \"center\">Configuration</h1>"
  },
  {
   "title": "Total Upstream Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_upstream_bits_per_second_tx_total)/1000000000"
    }
   ]
  },
  {
   "title": "Upstream Total Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_upstream_packets_per_second_tx_total)"
    }
   ]
  },
  {
   "title": "Total Downstream Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_downstream_bits_per_second_rx_total)/1000000000"
    }
   ]
  },
  {
   "title": "Downstream Total Packets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_downstream_packets_per_second_rx_total)"
    }
   ]
  },
  {
   "title": "No. Service Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Service Groups" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(collectd_upstream_average_frame_size_per_second_rx)"
    }
   ]
  },
  {
   "title": "Downstream Average Packet Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(collectd_downstream_bits_per_second_rx_total)/8)/sum(collectd_downstream_packets_per_second_rx_total)"
    }
   ]
  },
  {
   "title": "Upstream Average Packet Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(collectd_upstream_bits_per_second_tx_total)/8)/sum(collectd_upstream_packets_per_second_tx_total)"
    }
   ]
  },
  {
   "title": "Downstream Rx Dropped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_downstream_dropped_per_second_rx_total)"
    }
   ]
  },
  {
   "title": "Total Active Subscribers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Subscribers" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_downstream_active_cms_per_second_total)"
    }
   ]
  },
  {
   "title": "Upstream Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_upstream_dropped_per_second_rx_total)"
    }
   ]
  },
  {
   "title": "Scheduler Dropped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_downstream_sched_dropped_per_second_total)"
    }
   ]
  },
  {
   "title": "Upstream Throughput per Service Group (Gbps)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "collectd_upstream_bits_per_second_rx_total/1000000000",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Downstream Throughput per Service Group (Gbps)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "collectd_downstream_bits_per_second_rx_total/1000000000",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Wall and CPU Socket Power Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "collectd_ipmi_power{ipmi=\"PS1 Input Power power_supply (10.1)\"}",
     "legendFormat": "Wall Power"
    },
    {
     "expr": "sum(collectd_turbostat_power{exported_instance=\"localhost\",instance=\"localhost:9103\",job=\"collectd\",type=\"DRAM\"})",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(collectd_turbostat_power{exported_instance=\"localhost\",instance=\"localhost:9103\",job=\"collectd\",type=\"pkg\"})",
     "legendFormat": "CPU"
    },
    { "expr": "collectd_package_0_power_power", "legendFormat": "{{exported_instance}}-CPU0" },
    { "expr": "collectd_package_1_power_power", "legendFormat": "{{exported_instance}}-CPU1" }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "collectd_mem_bw_bytes", "legendFormat": "Memory Bandwidth" }
   ]
  }
 ]
}