{
 "title": "Upstream Processing (Per SG)",
 "tags": [ "vCMTS" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Scenario_One",
    "query": "SHOW TAG Values with key =\"host\""
   },
   {
    "name": "Scenario_Two",
    "query": "SHOW TAG Values with key =\"host\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 align = \"center\">$Scenario_One</h1>"
   },
   "content": "<h1 align = \"center\">$Scenario_One</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<h1 align = \"center\">$Scenario_Two</h1>"
   },
   "content": "<h1 align = \"center\">$Scenario_Two</h1>"
  },
  {
   "title": "L2TP Frame RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_bits_per_second_rx_total{exported_instance=\"$Scenario_One\"}/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_per_second_rx{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_bits_per_second_tx_total{exported_instance=\"$Scenario_One\"}/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_per_second_tx{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Frame RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_bits_per_second_rx_total{exported_instance=\"$Scenario_Two\"}/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "query": "SELECT distinct(\"value\") /1000000000 FROM \"upstream_rx\" WHERE (\"type\" = 'bits_per_second' AND \"type_instance\" = 'rx') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "RX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_per_second_rx{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_bits_per_second_tx_total{exported_instance=\"$Scenario_Two\"}/1000000000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_per_second_tx{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_rx{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_tx{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_rx{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_frame_size_tx{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_dropped_per_second_rx_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_dropped_per_second_tx_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_dropped_per_second_rx_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_dropped_per_second_tx_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TX",
     "expr": "collectd_upstream_upstream_cycles_rx{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "RX",
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "expr": "collectd_upstream_upstream_cycles_uepi_verification{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "UEPI Verification"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_uepi_decap{exported_instance=\"$Scenario_One\"}",
     "legendFormat": "UEPI Decap"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_docsis_segment_reassembly{exported_instance=\"$Scenario_One\"}",
     "legendFormat": "DOCSIS Segment Reassembly"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_docsis_frame_extraction{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "DOCSIS Frame Extraction"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_decryption_crc{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Decryption & CRC"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_tx{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Latency",
     "expr": "collectd_upstream_packet_latency_jitter{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Jitter",
     "measurement": "upstream_average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packet_latency" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_upstream_packet_latency_average{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TX",
     "expr": "collectd_upstream_upstream_cycles_rx{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "legendFormat": "RX",
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "expr": "collectd_upstream_upstream_cycles_uepi_verification{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "UEPI Verification"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_uepi_decap{exported_instance=\"$Scenario_Two\"}",
     "legendFormat": "UEPI Decap"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_docsis_segment_reassembly{exported_instance=\"$Scenario_Two\"}",
     "legendFormat": "DOCSIS Segment Reassembly"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_docsis_frame_extraction{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "DOCSIS Frame Extraction"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_decryption_crc{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Decryption & CRC"
    },
    {
     "expr": "collectd_upstream_upstream_cycles_tx{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average Latency",
     "expr": "collectd_upstream_packet_latency_jitter{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Jitter",
     "measurement": "upstream_average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packet_latency" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "expr": "collectd_upstream_packet_latency_average{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Empty",
     "expr": "collectd_upstream_rx_dequeue_per_second_pkts_not_present_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Empty",
     "measurement": "upstream_pkts_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "expr": "collectd_upstream_rx_dequeue_per_second_pkts_present_total{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Non-Empty"
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Empty",
     "expr": "collectd_upstream_rx_dequeue_per_second_pkts_not_present_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Empty",
     "measurement": "upstream_pkts_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "expr": "collectd_upstream_rx_dequeue_per_second_pkts_present_total{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Non-Empty"
    }
   ]
  },
  {
   "title": "CM Lookup",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "expr": "collectd_upstream_cm_lookup_unmatched{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Unmatched",
     "measurement": "upstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "expr": "collectd_upstream_cm_lookup_matched{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Matched"
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_packets_per_cm_lookup{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "CM Lookup",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "expr": "collectd_upstream_cm_lookup_unmatched{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Unmatched",
     "measurement": "upstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "expr": "collectd_upstream_cm_lookup_matched{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Matched"
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_packets_per_cm_lookup{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_active_cms_per_second_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_active_cms_per_second_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_ip_addr_per_cm{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_ip_addr_per_cm{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Valid",
     "expr": "\r\n\r\ncollectd_upstream_l2tp_verify_invalid{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Invalid",
     "measurement": "upstream_valid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    },
    {
     "expr": "collectd_upstream_l2tp_verify_valid{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "UEPI Frames",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Full",
     "expr": "collectd_upstream_uepi_frames_partial{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Partial",
     "measurement": "upstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    },
    {
     "expr": "collectd_upstream_uepi_frames_full{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Full"
    }
   ]
  },
  {
   "title": "L2TP Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Valid",
     "expr": "\r\n\r\ncollectd_upstream_l2tp_verify_invalid{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Invalid",
     "measurement": "upstream_valid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    },
    {
     "expr": "collectd_upstream_l2tp_verify_valid{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "UEPI Frames",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Full",
     "expr": "collectd_upstream_uepi_frames_partial{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Partial",
     "measurement": "upstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    },
    {
     "expr": "collectd_upstream_uepi_frames_full{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Full"
    }
   ]
  },
  {
   "title": "UEPI Drops per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_uepi_drops_per_second_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_drops_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_uepi_frames_per_second_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Drops per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_uepi_drops_per_second_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_drops_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_uepi_frames_per_second_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frame Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OFDMA",
     "expr": "collectd_upstream_uepi_frame_type_sc_qam{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "SC QAM",
     "measurement": "upstream_ofdma",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    },
    {
     "expr": "collectd_upstream_uepi_frame_type_ofdma{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "OFDMA"
    }
   ]
  },
  {
   "title": "Content Per Uepi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "data",
     "expr": "collectd_upstream_content_per_uepi_other{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Other",
     "measurement": "upstream_psp_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_trailer{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Trailer"
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_header{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Header"
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_data{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "UEPI Frame Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OFDMA",
     "expr": "collectd_upstream_uepi_frame_type_sc_qam{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "SC QAM",
     "measurement": "upstream_ofdma",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    },
    {
     "expr": "collectd_upstream_uepi_frame_type_ofdma{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "OFDMA"
    }
   ]
  },
  {
   "title": "Content Per Uepi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "data",
     "expr": "collectd_upstream_content_per_uepi_other{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Other",
     "measurement": "upstream_psp_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_trailer{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Trailer"
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_header{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Header"
    },
    {
     "expr": "collectd_upstream_content_per_uepi_psp_data{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "title": "DOCSIS Reasembly",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_docsis_reassembly_fail{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    },
    {
     "expr": "collectd_upstream_docsis_reassembly_success{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "HCS Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_hcs_verify_fail{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Fail",
     "expr": "collectd_upstream_hcs_verify_success{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Success",
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Reasembly",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_docsis_reassembly_fail{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    },
    {
     "expr": "collectd_upstream_docsis_reassembly_success{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "HCS Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_hcs_verify_fail{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Fail",
     "expr": "collectd_upstream_hcs_verify_success{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Success",
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per UEPI",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_uepi{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_frames_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Segment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_segment{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_segment" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per UEPI",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_uepi{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_frames_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Segment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_segment{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_segment" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Average DOCSIS Segment Length",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_docsis_segment_length{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_docsis_segment_length" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_docsis_frames_per_second_total{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Average DOCSIS Segment Length",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_upstream_average_docsis_segment_length{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_docsis_segment_length" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "expr": "collectd_upstream_crypto_accel_none{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "upstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "expr": "collectd_upstream_crypto_accel_qat{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "QAT"
    },
    {
     "expr": "collectd_upstream_crypto_accel_aesni{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "AESNI"
    }
   ]
  },
  {
   "title": "Crypto Algo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AES",
     "expr": "collectd_upstream_crypto_algo_none{exported_instance=\"$Scenario_One\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "upstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "expr": "collectd_upstream_crypto_algo_des{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "DES"
    },
    {
     "expr": "collectd_upstream_crypto_algo_aes{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "AES"
    }
   ]
  },
  {
   "title": "CRC Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_crc_verify_fail{exported_instance=\"$Scenario_One\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    },
    {
     "expr": "collectd_upstream_crc_verify_success{exported_instance=\"$Scenario_One\"}\t",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "expr": "collectd_upstream_crypto_accel_none{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "upstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "expr": "collectd_upstream_crypto_accel_qat{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "QAT"
    },
    {
     "expr": "collectd_upstream_crypto_accel_aesni{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "AESNI"
    }
   ]
  },
  {
   "title": "Crypto Algo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AES",
     "expr": "collectd_upstream_crypto_algo_none{exported_instance=\"$Scenario_Two\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "None",
     "measurement": "upstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "expr": "collectd_upstream_crypto_algo_des{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "DES"
    },
    {
     "expr": "collectd_upstream_crypto_algo_aes{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "AES"
    }
   ]
  },
  {
   "title": "CRC Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "expr": "collectd_upstream_crc_verify_fail{exported_instance=\"$Scenario_Two\"}\t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fail",
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    },
    {
     "expr": "collectd_upstream_crc_verify_success{exported_instance=\"$Scenario_Two\"}\t",
     "legendFormat": "Success"
    }
   ]
  }
 ]
}