apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vcmts-nw-vf-socket-0-us
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  nicSelector:
    deviceID: '1592'
    pfNames:
      - 'ens785f0#0-0'
      - 'ens785f0#2-2'
      - 'ens785f0#4-4'
      - 'ens785f0#6-6'
      - 'ens785f1#0-0'
      - 'ens785f1#2-2'
      - 'ens785f1#4-4'
      - 'ens785f1#6-6'
    vendor: '8086'
  nodeSelector:
    node-role.kubernetes.io/vcmts: ''
  numVfs: 8
  priority: 99
  resourceName: vcmts_nw_vf_socket_0_us
