apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vcmts-us-0
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  nicSelector:
    deviceID: '1592'
    pfNames:
      - 'ens785f1#4-7'
    vendor: '8086'
  nodeSelector:
    node-role.kubernetes.io/vcmts: ''
  numVfs: 8
  priority: 99
  resourceName: vcmts_nw_vf_us_0
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vcmts-us-1
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  nicSelector:
    deviceID: '1592'
    pfNames:
      - 'ens786f1#4-7'
    vendor: '8086'
  nodeSelector:
    node-role.kubernetes.io/vcmts: ''
  numVfs: 8
  priority: 99
  resourceName: vcmts_nw_vf_us_1
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vcmts-us-2
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  nicSelector:
    deviceID: '1592'
    pfNames:
      - 'ens801f1#4-7'
    vendor: '8086'
  nodeSelector:
    node-role.kubernetes.io/vcmts: ''
  numVfs: 8
  priority: 99
  resourceName: vcmts_nw_vf_us_2
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vcmts-us-3
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  nicSelector:
    deviceID: '1592'
    pfNames:
      - 'ens802f1#4-7'
    vendor: '8086'
  nodeSelector:
    node-role.kubernetes.io/vcmts: ''
  numVfs: 8
  priority: 99
  resourceName: vcmts_nw_vf_us_3
---
