apiVersion: v1
kind: Pod
metadata:
  name: pcm
  labels:
    app: pcm
  namespace: vcmts-build
spec:
  nodeSelector:
    vcmts: "true"
  containers:
    - name: pcm
      securityContext:
        privileged: true
      image: image-registry.openshift-image-registry.svc:5000/vcmts-build/vcmts-pcm:21.10.0
      command: ["/bin/sh"]
      args: ["-c", "./get_bandwidth_pcm.sh /home/vcmts"]
      imagePullPolicy: Always
      volumeMounts:
        - name: pcm-monitoring
          mountPath: /root/get_bandwidth_pcm.sh
          subPath: get_bandwidth_pcm.sh
        - name: collectd
          mountPath: /opt/collectd/var/run/collectd.sock
          readOnly: false
        - name: mcfg
          mountPath: /pcm/sys/firmware/acpi/tables/MCFG
          readOnly: true
        - name: pci
          mountPath: /pcm/proc/bus/pci/
          readOnly: false
        - name: nmi-watchdog
          mountPath: /pcm/proc/sys/kernel/nmi_watchdog
          readOnly: false
        - name: cpu
          mountPath: /dev/cpu
          readOnly: false
        - name: mem
          mountPath: /dev/mem
          readOnly: false
  volumes:
    - name: pcm-monitoring
      configMap:
        name: pcm-monitoring
        defaultMode: 0777
    - name: collectd
      hostPath:
        path: /var/run/collectd/collectd.sock
        type: Socket
    - name: mcfg
      hostPath:
        path: /sys/firmware/acpi/tables/MCFG
    - name: pci
      hostPath:
        path: /proc/bus/pci/
    - name: nmi-watchdog
      hostPath:
        path: /proc/sys/kernel/nmi_watchdog
    - name: cpu
      hostPath:
        path: /dev/cpu
    - name: mem
      hostPath:
        path: /dev/mem