apiVersion: v1
kind: Pod
metadata:
  name: config-pktgen
  namespace: vcmts-build
spec:
  containers:
    - name: config-pktgen
      image: docker.io/adetalhouet/socat
      command:
        - /bin/bash
        - -c
        - sleep infinity
      volumeMounts:
        - name: config-pktgen
          mountPath: /opt/scripts
  restartPolicy: Never
  serviceAccount: pipeline
  serviceAccountName: pipeline
  volumes:
    - name: config-pktgen
      configMap:
        name: config-pktgen
        defaultMode: 0777