apiVersion: batch/v1
kind: Job
metadata:
  name: config-pktgen
  namespace: vcmts-build
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: config-pktgen
    spec:
      containers:
        - name: config-pktgen
          image: docker.io/adetalhouet/socat
          env:
          - name: UPSTREAM_RATE  
            value: "10"
          - name: DOWNSTREAM_RATE
            value: "10"
          - name: START
            value: "false"
          - name: STOP
            value: "true"
          command:
            - /bin/bash
            - -c
            - |
              cp /root/pktgen-config.lua config.lua
              sed -i "s/DOWNSTREAM_RATE/$DOWNSTREAM_RATE/" config.lua
              sed -i "s/UPSTREAM_RATE/$UPSTREAM_RATE/" config.lua
              sed -i "s/START/$START/" config.lua
              sed -i "s/STOP/$STOP/" config.lua

              PKTGEN_IPS=$(oc get pods -n vcmts-build -l name=pktgen -o jsonpath='{.items[*].status.podIP}')
              PKTGEN_IP_ARRAY=($(echo $PKTGEN_IPS | tr ";" "\n"))
              i=23000
              for ip in "${PKTGEN_IP_ARRAY[@]}"
              do
                  socat - TCP4:$ip:$i < config.lua
                  ((i=i+1))
              done
          volumeMounts:
            - name: config-pktgen
              mountPath: /root/pktgen-config.lua
              subPath: pktgen-config.lua
      restartPolicy: Never
      serviceAccount: pipeline
      serviceAccountName: pipeline
      volumes:
        - name: config-pktgen
          configMap:
            name: config-pktgen