apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pktgen
  namespace: vcmts-build
data:
  set-qat.sh: |
    #!/bin/bash

    cp pktgen-set.lua ../config.lua
    sed -i "s/STREAM/$1/" ../config.lua
    sed -i "s/RATE/$2/" ../config.lua

    i=0
    VCMTSD_PODS=$(oc get pods -n vcmts-build --sort-by=.metadata.name -o name | grep vcmtsd)
    VCMTSD_PODS_ARRAY=($(echo $VCMTSD_PODS | tr ";" "\n")) 
    for vcmtsd in "${VCMTSD_PODS_ARRAY[@]}"
    do
      oc rsh -n vcmts-build $vcmtsd env | grep QAT=true
      if [[ $? == 0 ]]; then
        PORT=$((23000+$i))
        QAT_SG_PKGEN_IP=$(oc get pod -n vcmts-build vcmts-pktgen-pod-$i -o jsonpath='{.status.podIP}')
        socat - TCP4:$QAT_SG_PKGEN_IP:$PORT < ../config.lua
      fi
      ((i=i+1))
    done

    rm ../config.lua
  set.sh: |
    #!/bin/bash

    cp pktgen-set.lua ../config.lua
    sed -i "s/STREAM/$1/" ../config.lua
    sed -i "s/RATE/$2/" ../config.lua

    i=0
    VCMTSD_PODS=$(oc get pods -n vcmts-build --sort-by=.metadata.name -o name | grep vcmtsd)
    VCMTSD_PODS_ARRAY=($(echo $VCMTSD_PODS | tr ";" "\n")) 
    for vcmtsd in "${VCMTSD_PODS_ARRAY[@]}"
    do
      oc rsh -n vcmts-build $vcmtsd env | grep QAT=false
      if [[ $? == 0 ]]; then
        PORT=$((23000+$i))
        QAT_SG_PKGEN_IP=$(oc get pod -n vcmts-build vcmts-pktgen-pod-$i -o jsonpath='{.status.podIP}')
        socat - TCP4:$QAT_SG_PKGEN_IP:$PORT < ../config.lua
      fi
      ((i=i+1))
    done

    rm ../config.lua
  start.sh: |
    #!/bin/bash
    PKTGEN_IPS=$(oc get pods -n vcmts-build -l name=pktgen --sort-by=.metadata.name -o jsonpath='{.items[*].status.podIP}')
    PKTGEN_IP_ARRAY=($(echo $PKTGEN_IPS | tr ";" "\n"))
    i=23000
    for ip in "${PKTGEN_IP_ARRAY[@]}"
    do
        socat - TCP4:$ip:$i < pktgen-start.lua
        ((i=i+1))
    done
  stop.sh: |
    #!/bin/bash
    PKTGEN_IPS=$(oc get pods -n vcmts-build -l name=pktgen --sort-by=.metadata.name -o jsonpath='{.items[*].status.podIP}')
    PKTGEN_IP_ARRAY=($(echo $PKTGEN_IPS | tr ";" "\n"))
    i=23000
    for ip in "${PKTGEN_IP_ARRAY[@]}"
    do
        socat - TCP4:$ip:$i < pktgen-stop.lua
        ((i=i+1))
    done
  pktgen-set.lua: |
    package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
    pktgen.set("STREAM", "rate", "RATE");
  pktgen-start.lua: |
    package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
    pktgen.start("all");
  pktgen-stop.lua: |
    package.path = package.path ..";?.lua;test/?.lua;app/?.lua;"
    pktgen.stop("all");
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pktgen
  namespace: vcmts-build
  labels:
    app: pktgen-helper
spec:
  containers:
    - name: config-pktgen
      image: docker.io/adetalhouet/socat
      command:
        - /bin/bash
        - -c
        - sleep infinity
      volumeMounts:
        - name: config-pktgen
          mountPath: /opt/scripts
  restartPolicy: Never
  serviceAccount: pipeline
  serviceAccountName: pipeline
  volumes:
    - name: config-pktgen
      configMap:
        name: config-pktgen
        defaultMode: 0777