apiVersion: deviceplugin.intel.com/v1
kind: QatDevicePlugin
metadata:
  name: qat-device-plugin
  namespace: inteldeviceplugins-system
  annotations:
    container.apparmor.security.beta.kubernetes.io/intel-qat-plugin: unconfined
spec:
  image: intel/intel-qat-plugin:0.23.0
  dpdkDriver: vfio-pci
  kernelVfDrivers:
    - c6xxvf
    - 4xxxvf
  maxNumDevices: 96
  logLevel: 4
  nodeSelector:
    vcmts: 'true'
