apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  namespace: openshift-sriov-network-operator
  name: pktgen-us-0
spec:
  networkNamespace: pktgen-build
  resourceName: pktgen_nw_vf_us_0
  spoofChk: 'off'
  trust: 'on'
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  namespace: openshift-sriov-network-operator
  name: pktgen-us-1
spec:
  networkNamespace: pktgen-build
  resourceName: pktgen_nw_vf_us-1
  spoofChk: 'off'
  trust: 'on'
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  namespace: openshift-sriov-network-operator
  name: pktgen-us-2
spec:
  networkNamespace: pktgen-build
  resourceName: pktgen_nw_vf_us-2
  spoofChk: 'off'
  trust: 'on'
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  namespace: openshift-sriov-network-operator
  name: pktgen-us-3
spec:
  networkNamespace: pktgen-build
  resourceName: pktgen_nw_vf_us-3
  spoofChk: 'off'
  trust: 'on'