apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-nfd-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-nfd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace