apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  labels:
    app: vcmts
  name: vcmts
  namespace: vcmts-build
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: vcmts
      admin_user: vcmts
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - vcmts
  ingress:
    enabled: true