apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: vcmts
  labels:
    custom-kubelet: max-pods-500
    machineconfiguration.openshift.io/role: vcmts
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - vcmts
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/vcmts: ''